#!/bin/bash
set -eux

source /etc/sysconfig/undercloud-live-config || true
LEAF_IP=${LEAF_IP:-192.0.2.2}
CONTROL_INTERFACE=${CONTROL_INTERFACE:-eth0}

sudo ip route del 192.0.2.0/24 dev $CONTROL_INTERFACE || true
sudo ip route add 192.0.2.0/24 dev $CONTROL_INTERFACE via $LEAF_IP || true
