#!/bin/bash
set -eu

OK=/opt/stack/boot-stack/metadata-iptables.ok

if [ -e $OK ] ; then
    exit 0
fi

DISTRO=`lsb_release -si` || true

source /etc/sysconfig/undercloud-live-config || true
CONTROL_IP=${CONTROL_IP:-192.0.2.1}

if [[ "Fedora" = $DISTRO ]]; then

    # Check if the iptables service is active
    if systemctl is-active iptables.service ; then
        IPT_FILE=/etc/sysconfig/iptables
        if [ -f $IPT_FILE ]; then
            iptables-restore < $IPT_FILE
        fi

        iptables -t nat -I PREROUTING -d 169.254.169.254/32 -i br-ctlplane -p tcp -m tcp --dport 80 -j DNAT --to-destination $CONTROL_IP:8775
        iptables -t nat -I PREROUTING -d 192.0.2.1/32 -i br-ctlplane -p tcp -m tcp --dport 8000 -j DNAT --to-destination $CONTROL_IP:8000

        iptables-save > $IPT_FILE
    fi

fi

touch $OK
