#!/bin/bash

source /etc/sysconfig/undercloud-live-config || true

UNDERCLOUD_CONTROL_IP=${UNDERCLOUD_CONTROL_IP:-192.0.2.1}
UNDERCLOUD_LEAF_IP=${UNDERCLOUD_LEAF_IP:-192.0.2.2}
CONTROL_PUBLIC_INTERFACE=${CONTROL_PUBLIC_INTERFACE:-eth0}
LEAF_PUBLIC_INTERFACE=${LEAF_PUBLIC_INTERFACE:-eth0}

sudo sed -i "s/192.0.2.1/$UNDERCLOUD_CONTROL_IP/g" /var/lib/heat-cfntools/cfn-init-data
sudo sed -i "s/eth1/$LEAF_PUBLIC_INTERFACE/g" /var/lib/heat-cfntools/cfn-init-data
