#!/bin/bash
set -eux

install -D -m 0755 -o root -g root $(dirname $0)/../undercloud-metadata /usr/local/bin/undercloud-metadata

# Set some sane defaults where they make sense
CONTROL_INTERFACE=${CONTROL_INTERFACE:-eth0}
LEAF_INTERFACE=${LEAF_INTERFACE:=eth1}
CONTROL_IP=${CONTROL_IP:-""}
LEAF_IP=${LEAF_IP:-192.0.2.1}
NODE_CPU=${NODE_CPU:-1}
NODE_MEM=${NODE_MEM:-2048}
NODE_DISK=${NODE_DISK:-20}
NODE_ARCH=${NODE_ARCH:-amd64}
UNDERCLOUD_MACS=${UNDERCLOUD_MACS:-""}
LIBVIRT_HOST=${LIBVIRT_HOST:-192.168.122.1}
LIBVIRT_USER=${LIBVIRT_USER:-stack}


cat >> /etc/sysconfig/undercloud-live-config << EOQ
export CONTROL_IP=$CONTROL_IP
export LEAF_IP=$LEAF_IP
export CONTROL_INTERFACE=$CONTROL_INTERFACE
export LEAF_INTERFACE=$LEAF_INTERFACE

export NODE_CPU=$NODE_CPU
export NODE_MEM=$NODE_MEM
export NODE_DISK=$NODE_DISK
export NODE_ARCH=$NODE_ARCH

export UNDERCLOUD_MACS="$UNDERCLOUD_MACS"

export LIBVIRT_HOST=$LIBVIRT_HOST
export LIBVIRT_USER=$LIBVIRT_USER
EOQ
