#!/bin/bash

# iptables should be used, not firewalld

# It's okay for this to fail - firewalld may not be installed
sudo systemctl stop firewalld || true
sudo systemctl disable firewalld || true
sudo systemctl mask firewalld || true

touch /etc/sysconfig/iptables
systemctl enable iptables
systemctl start iptables
systemctl enable ip6tables
systemctl start ip6tables
