#!/bin/bash
set -eux

mkdir -p /var/lib/cloud/data
# installed as config.json because undercloud-metadata still performs a
# substitution that creates cfn-init-data
install -D -m 0755 -o root -g root $(dirname $0)/../config.json /var/lib/heat-cfntools/config.json
