#!/bin/bash

source /etc/sysconfig/undercloud-live-config || true

sed_commands="
    s/CONTROL_IP/$CONTROL_IP/g
    s/CONTROL_INTERFACE/$CONTROL_INTERFACE/g
    s/LEAF_INTERFACE/$LEAF_INTERFACE/g
    s/LEAF_IP/$LEAF_IP/g
    s/LEAF_SERVICE_HOST/$LEAF_SERVICE_HOST/g
    s/LIBVIRT_HOST/$LIBVIRT_HOST/g
    s/LIBVIRT_USER/$LIBVIRT_USER/g
"

echo "Writing /var/lib/heat-cfntools/cfn-init-data"
sed -e "$sed_commands" /var/lib/heat-cfntools/config.json > /var/lib/heat-cfntools/cfn-init-data

sudo rm -f /opt/stack/boot-stack/metadata-iptables.ok

echo -n "Restarting os-collect-config...."
sudo systemctl restart os-collect-config
echo "Done."

echo "You may want to watch it's progress by running:"
echo "sudo journalctl --full -f -u os-collect-config"
