#!/bin/bash

source /etc/sysconfig/undercloud-live-config || true

sed_commands="
    s/CONTROL_IP/$CONTROL_IP/g
    s/CONTROL_INTERFACE/$CONTROL_INTERFACE/g
    s/LEAF_INTERFACE/$LEAF_INTERFACE/g
    s/LIBVIRT_HOST/$LIBVIRT_HOST/g
    s/LIBVIRT_USER/$LIBVIRT_USER/g
"

sed -e "$sed_commands" /var/lib/heat-cfntools/config.json > /var/lib/heat-cfntools/cfn-init-data
